// eslint-disable-next-line
export default [
  {
    modell: "Kia Soul",
    årsmodell: 2021,
    hentested: "St.Hanshaugen",
    ledige_uker: [1, 2, 3, 4, 9, 12],
    biltype: "Personbil",
    drivstoff: "Elektrisitet",
    girkasse: "Automat",
  },
  {
    modell: "Hyundai Kona",
    årsmodell: 2020,
    hentested: "Røa",
    ledige_uker: [1, 2, 9],
    biltype: "Personbil",
    drivstoff: "Elektrisitet",
    girkasse: "Automat",
  },
  {
    modell: "Toyota Yaris",
    årsmodell: 2012,
    hentested: "Ulsrud",
    ledige_uker: [1, 9, 12],
    biltype: "Personbil",
    drivstoff: "Bensin",
    girkasse: "Manuell",
  },
  {
    modell: "Volvo S40",
    årsmodell: 2007,
    hentested: "Oppegård",
    ledige_uker: [1, 2, 4, 9],
    biltype: "Personbil",
    drivstoff: "Bensin",
    girkasse: "Automat",
  },
  {
    modell: "Tesla Model S",
    årsmodell: 2015,
    hentested: "Moss",
    ledige_uker: [1, 2],
    biltype: "Personbil",
    drivstoff: "Elektrisitet",
    girkasse: "Automat",
  },
  {
    modell: "Tesla Model X",
    årsmodell: 2020,
    hentested: "Vestby",
    ledige_uker: [4, 9, 12, 13],
    biltype: "Personbil",
    drivstoff: "Elektrisitet",
    girkasse: "Automat",
  },
  {
    modell: "Toyota RAV4",
    årsmodell: 2017,
    hentested: "Rygge",
    ledige_uker: [1, 2, 4, 9],
    biltype: "SUV",
    drivstoff: "Diesel",
    girkasse: "Automat",
  },
  {
    modell: "Toyota Corolla",
    årsmodell: 2016,
    hentested: "Oppsal",
    ledige_uker: [2, 4, 9, 13],
    biltype: "Stasjonsvogn",
    drivstoff: "Bensin",
    girkasse: "Manuell",
  },
  {
    modell: "Nissal Leaf",
    årsmodell: 2019,
    hentested: "Ås",
    ledige_uker: [4, 12, 13],
    biltype: "Personbil",
    drivstoff: "Elektrisitet",
    girkasse: "Automat",
  },
  {
    modell: "Ford Transit",
    årsmodell: 2017,
    hentested: "Grefsen",
    ledige_uker: [1, 2, 4, 9, 12, 13],
    biltype: "Varebil",
    drivstoff: "Bensin",
    girkasse: "Manuell",
  },
  {
    modell: "Volkswagen Caddy",
    årsmodell: 2010,
    hentested: "Sarpsborg",
    ledige_uker: [1, 2, 4, 9, 12, 13],
    biltype: "Varebil",
    drivstoff: "Diesel",
    girkasse: "Automat",
  },
  {
    modell: "Mitsubishi Outlander",
    årsmodell: 2016,
    hentested: "Fagerstrand",
    ledige_uker: [1, 4, 9],
    biltype: "SUV",
    drivstoff: "Hybrid",
    girkasse: "Automat",
  },
  {
    modell: "BMW i3",
    årsmodell: 2021,
    hentested: "Fredrikstad",
    ledige_uker: [1, 2, 4, 9],
    biltype: "Personbil",
    drivstoff: "Elektrisitet",
    girkasse: "Automat",
  },
  {
    modell: "Ford Focus",
    årsmodell: 2008,
    hentested: "Holmlia",
    ledige_uker: [1, 2, 4, 9, 13],
    biltype: "Stasjonsvogn",
    drivstoff: "Bensin",
    girkasse: "Manuell",
  },
  {
    modell: "Skoda Superb",
    årsmodell: 2016,
    hentested: "Ski",
    ledige_uker: [2, 4, 13],
    biltype: "Stasjonsvogn",
    drivstoff: "Diesel",
    girkasse: "Automat",
  },
  {
    modell: "Volkswagen Golf",
    årsmodell: 2015,
    hentested: "Jessheim",
    ledige_uker: [1, 2, 4, 9, 12, 13],
    biltype: "Personbil",
    drivstoff: "Bensin",
    girkasse: "Automat",
  },
  {
    modell: "Volkswagen Polo",
    årsmodell: 2017,
    hentested: "Nittedal",
    ledige_uker: [2, 9, 11],
    biltype: "Personbil",
    drivstoff: "Bensin",
    girkasse: "Automat",
  },
  {
    modell: "Ford Mondeo",
    årsmodell: 2019,
    hentested: "Sandefjord",
    ledige_uker: [2, 9, 10, 11, 13],
    biltype: "Stasjonsvogn",
    drivstoff: "Bensin",
    girkasse: "Automat",
  },
  {
    modell: "Renault Zoe",
    årsmodell: 2018,
    hentested: "Hauketo",
    ledige_uker: [2, 9, 10, 11, 13],
    biltype: "Personbil",
    drivstoff: "Elektrisitet",
    girkasse: "Automat",
  },
  {
    modell: "Toyota HiAce",
    årsmodell: 2003,
    hentested: "Drøbak",
    ledige_uker: [2, 9, 11, 13, 14],
    biltype: "Varebil",
    drivstoff: "Bensin",
    girkasse: "Manuell",
  },
];
